version: '3'
services:
  geoserver:
    image: oscarfonts/geoserver:2.12.3
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - "./geoserver:/var/local/geoserver"
      - "./extensions:/var/local/geoserver-exts"


