version: '3'
services:
  db:
    image: kartoza/postgis:9.6-2.4
    ports:
      - "65432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASS=admin
      - POSTGRES_DBNAME=geoserver
  geoserver:
    image: oscarfonts/geoserver:2.12.3
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - "./geoserver:/var/local/geoserver"
      - "./extensions:/var/local/geoserver-exts"


